//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microservice.PSE.Api.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microservice.PSE.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Un error de negocio ha ocurrido: {0}.
        /// </summary>
        internal static string BusinessError
        {
            get
            {
                return ResourceManager.GetString("BusinessError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La configuración de la base de datos no existe..
        /// </summary>
        internal static string DataBaseConfigurationError
        {
            get
            {
                return ResourceManager.GetString("DataBaseConfigurationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ya se encuentra un banco con el código {0} en la base de datos..
        /// </summary>
        internal static string EntityAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("EntityAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La creación del banco {0}, se realizó correctamente.
        /// </summary>
        internal static string EntityCreatedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EntityCreatedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El banco se ha eliminado correctamente..
        /// </summary>
        internal static string EntityDeleteSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EntityDeleteSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El banco con identificador {0} no se encontró en la base de datos.
        /// </summary>
        internal static string EntityNotExists
        {
            get
            {
                return ResourceManager.GetString("EntityNotExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La actualización del banco {0}, se realizó correctamente..
        /// </summary>
        internal static string EntityUpdateSuccessfully
        {
            get
            {
                return ResourceManager.GetString("EntityUpdateSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error no controlado en la aplicación. contacte al administrador del sistema. Id: {0}.
        /// </summary>
        internal static string GeneralApplicationError
        {
            get
            {
                return ResourceManager.GetString("GeneralApplicationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El banco con código {0} está inactivo y no puede ser utilizado.
        /// </summary>
        internal static string InactiveBankError
        {
            get
            {
                return ResourceManager.GetString("InactiveBankError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El banco con código {0} no es válido o no existe.
        /// </summary>
        internal static string InvalidBankError
        {
            get
            {
                return ResourceManager.GetString("InvalidBankError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer comunicación con la API del banco {0}. El servicio no está disponible.
        /// </summary>
        internal static string BankApiError
        {
            get
            {
                return ResourceManager.GetString("BankApiError", resourceCulture);
            }
        }
    }
}